databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: hello@teamcfe.com
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: cfe
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: r1o$%mf1%&u4eusta^7qq3nt&v*i@ks^(!siy5qhj-6)&rlx$0
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: r1o$%mf1%&u4eusta^7qq3nt&v*i@ks^(!siy5qhj-6)&rlx$0
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: r1o$%mf1%&u4eusta^7qq3nt&v*i@ks^(!siy5qhj-6)&rlx$0
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: r1o$%mf1%&u4eusta^7qq3nt&v*i@ks^(!siy5qhj-6)&rlx$0
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: trydjango32
- key: OCR_API_TOKEN_HEADER
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: r1o$%mf1%&u4eusta^7qq3nt&v*i@ks^(!siy5qhj-6)&rlx$0
- key: OCR_API_ENDPOINT
  scope: RUN_AND_BUILD_TIME
  value: https://fastapi-microservice-for-django-d3kjd.ondigitalocean.app
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: production-3
    deploy_on_push: true
    repo: ryankSD/flayver
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: python manage.py migrate --noinput
  source_dir: /
name: try-django-3-2
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: production-3
    deploy_on_push: true
    repo: ryankSD/flayver
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: try-django-3-2
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /
